server:
  port : 80
  error:
    include-message: always
    whitelabel:
      enabled: false
redis:
  host: redis-13023.c245.us-east-1-3.ec2.cloud.redislabs.com
  port: 13023
  password: "agRukI9hajlXJ603cvNPZBKf3P2H265X"
spring:
  application:
    name: unit-test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-146-91-153.compute-1.amazonaws.com:5432/d2qnmp2a7rdkk4
    username: jyqyzlawtqdxrd
    password: 3e10895c838508f06606797f2bfcdfe8ccdba9db060f244095ce7a8249f9df3c
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
unittest:
  session:
    expired:
      signing: 6000
swagger:
  host: "localhost:80"